#!/usr/bin/env bash
# ============================================================================
#  KDPD: TẠO LẠI FILE .env 100% SẠCH (không CRLF Windows, không ký tự > wrap dòng)
#  Chạy: bash kdpd-generate-clean-env.sh
#  Sau khi chạy xong, file .env sẽ được tạo lại 100% theo đúng format Unix LF
# ============================================================================
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Backup .env cũ nếu có (để đọc lại Google Client ID/Secret cũ làm default prompt sau này)
OLD_ENV_BACKUP=""
if [[ -f .env ]]; then
  OLD_ENV_BACKUP=".env.backup-before-clean-$(date +%Y%m%d-%H%M%S)"
  cp -a .env "$OLD_ENV_BACKUP"
  echo -e "\033[0;33m⚠️  Đã backup .env cũ → $OLD_ENV_BACKUP\033[0m"
  echo -e "(Nếu sau này cần khôi phục: cp -a '$OLD_ENV_BACKUP' .env)\n"
fi

# Trích xuất 2 giá trị Google từ backup cũ (nếu có) để làm default prompt (user chỉ cần Enter)
extract_old_env() {
  local key="$1"
  if [[ -n "${OLD_ENV_BACKUP}" ]] && [[ -f "$OLD_ENV_BACKUP" ]]; then
    grep -E "^[[:space:]]*${key}=" "$OLD_ENV_BACKUP" 2>/dev/null | head -1 | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//" | tr -d '\r' || true
  fi
}
OLD_GCID="$(extract_old_env GOOGLE_CLIENT_ID || true)"
OLD_GCSEC="$(extract_old_env GOOGLE_CLIENT_SECRET || true)"

echo -e "\033[1;36m═══════════════════════════════════════════════════════════\033[0m"
echo -e "\033[1;36m Bước 1/3: Nhập các giá trị BẮT BUỘC (các giá trị secret)\033[0m"
echo -e "\033[1;36m═══════════════════════════════════════════════════════════\033[0m"
echo ""
echo "  Bạn có thể dán giá trị vào đây (nhấn Enter khi xong)."
echo "  Để bỏ qua (dùng giá trị mặc định / mẫu), chỉ cần Enter không nhập gì."
echo ""

prompt_value() {
  # $1 = tên biến, $2 = ví dụ, $3 = mặc định nếu user chỉ nhấn Enter
  local varname="$1" example="$2" default="${3:-}"
  local val
  read -rp "  $varname (ví dụ: $example) → " val
  if [[ -z "${val:-}" ]]; then
    val="$default"
  fi
  echo "$val"
}

echo ""
DB_PASS=$(prompt_value "kdpd_user PostgreSQL PASSWORD" "mật_khẩu_của_kdpd_user_sau_khi_CHANGEME" "")
SESS_SEC=$(prompt_value "SESSION_SECRET (random 32 ký tự)" "openssl rand -hex 20" "$(openssl rand -hex 20 2>/dev/null || echo 'CHANGEME_TO_RANDOM_LONG_STRING_PLEASE_32CHARS')")
G_CID=$(prompt_value "GOOGLE_CLIENT_ID" "676277385515-...apps.googleusercontent.com" "${OLD_GCID:-}")
G_CSEC=$(prompt_value "GOOGLE_CLIENT_SECRET" "GOCSPX-... (khoảng 24 ký tự)" "${OLD_GCSEC:-}")
G_REFRESH=$(prompt_value "GOOGLE_REFRESH_TOKEN" "1//04Gt...full chuỗi gốc 200+ ký tự" "")
G_CAL_REDIR=$(prompt_value "GOOGLE_CALENDAR_REDIRECT_URI" "https://brotherlike-solicitous-anneliese.ngrok-free.app/api/google/calendar/oauth2callback" "")
GMAIL_APP_PW=$(prompt_value "Gmail app password (nếu dùng Gmail SMTP 2FA)" "16 ký tự app-specific password" "")

echo ""
echo -e "\033[1;36m═══════════════════════════════════════════════════════════\033[0m"
echo -e "\033[1;36m Bước 2/3: Tạo .env sạch (LF Unix, 0 ký tự > xen kẽ value)\033[0m"
echo -e "\033[1;36m═══════════════════════════════════════════════════════════\033[0m"

cat > .env <<'CLEAN_EOF'
# ============================================================
#  KDPD — ENVIRONMENT VARIABLES — CLEAN VERSION (LF Unix)
#  Generated by kdpd-generate-clean-env.sh
# ============================================================

# ── PostgreSQL DATABASE ─────────────────────────────────────
DATABASE_URL=postgresql://kdpd_user:__DB_PASS_PLACEHOLDER__@localhost:5433/kdpd_db?schema=public

# ── SERVER PORT & MODE ─────────────────────────────────────
PORT=5000
NODE_ENV=production
TRUST_PROXY=1

# ── SESSION & SECURITY ─────────────────────────────────────
SESSION_SECRET=__SESSION_SECRET_PLACEHOLDER__
SESSION_SECURE=false
CSRF_CHECK=true
CSRF_ORIGIN=http://task.kdpd.local,http://localhost:5173,http://localhost:3000,http://127.0.0.1:5000

# ── GMAIL / SMTP ───────────────────────────────────────────
GMAIL_USER=banthuky.kdpd@gmail.com
GMAIL_APP_PASSWORD=__GMAIL_APP_PW_PLACEHOLDER__
MAIL_FROM="KDPD System <banthuky.kdpd@gmail.com>"
MAIL_SUBJECT_PREFIX="[KDPD]"

# ── GOOGLE OAUTH2 (Login / Drive / Calendar) ───────────────
GOOGLE_CLIENT_ID=__G_CLIENT_ID_PLACEHOLDER__
GOOGLE_CLIENT_SECRET=__G_CLIENT_SECRET_PLACEHOLDER__
GOOGLE_REFRESH_TOKEN=__G_REFRESH_TOKEN_PLACEHOLDER__
GOOGLE_REDIRECT_URI=https://developers.google.com/oauthplayground
GOOGLE_CALENDAR_REDIRECT_URI=__G_CAL_REDIRECT_URI_PLACEHOLDER__

# ── BACKUP DATABASE (PG_DUMP / GOOGLE DRIVE) ───────────────
# PG_DUMP_PATH (chỉ Windows cần, Linux bỏ trống /usr/bin tìm thấy tự động):
# PG_DUMP_PATH=/usr/bin/pg_dump
# BACKUP_LOCAL_DIR=/home/kdpd-project/Task-Project/KDPD_PRJ_MNG/backups
# GOOGLE_DRIVE_FOLDER_ID=

# ── OPTIONAL CLOUD (Onedrive / MSAL — stub nếu dùng sau) ──
# AZURE_TENANT_ID=
# AZURE_CLIENT_ID=
# ONEDRIVE_FOLDER_ID=

# ── OTHER ──────────────────────────────────────────────────
CSP_ENABLED=false
CLEAN_EOF

# SỬA các placeholder bằng giá trị thật vừa nhập
if [[ -n "$DB_PASS" ]]; then sed -i "s|__DB_PASS_PLACEHOLDER__|$DB_PASS|g" .env; fi
if [[ -n "$SESS_SEC" ]]; then sed -i "s|__SESSION_SECRET_PLACEHOLDER__|$SESS_SEC|g" .env; fi
if [[ -n "$G_CID" ]]; then sed -i "s|__G_CLIENT_ID_PLACEHOLDER__|$G_CID|g" .env; fi
if [[ -n "$G_CSEC" ]]; then sed -i "s|__G_CLIENT_SECRET_PLACEHOLDER__|$G_CSEC|g" .env; fi
if [[ -n "$G_REFRESH" ]]; then sed -i "s|__G_REFRESH_TOKEN_PLACEHOLDER__|$G_REFRESH|g" .env; fi
if [[ -n "$G_CAL_REDIR" ]]; then sed -i "s|__G_CAL_REDIRECT_URI_PLACEHOLDER__|$G_CAL_REDIR|g" .env; fi
if [[ -n "$GMAIL_APP_PW" ]]; then sed -i "s|__GMAIL_APP_PW_PLACEHOLDER__|$GMAIL_APP_PW|g" .env; fi

# Đảm bảo LF Unix 100% (không còn CRLF)
if command -v dos2unix >/dev/null 2>&1; then dos2unix -q .env; else sed -i 's/\r$//' .env; fi

echo ""
echo -e "\033[0;32m✅ Đã tạo file .env mới.\033[0m"
echo -e "\033[1;36m═══════════════════════════════════════════════════════════\033[0m"
echo -e "\033[1;36m Bước 3/3: Kiểm tra 5 lỗi phổ biến\033[0m"
echo -e "\033[1;36m═══════════════════════════════════════════════════════════\033[0m"
echo ""

ERRORS=0

# Kiểm tra 1: Ký tự > xuất hiện trong value của 1 dòng (dấu hiệu wrap)
if grep -E '^[A-Z0-9_]+=.*>.*=' .env >/dev/null 2>&1 || \
   grep -E '^[A-Z0-9_]+=.+>[a-zA-Z]' .env | grep -v 'postgresql://\|http://\|https://' >/dev/null 2>&1; then
  echo -e "  \033[0;31m❌ Phát hiện ký tự > xen kẽ trong value env (dấu hiệu wrap dòng) → cần kiểm tra thủ công:\033[0m"
  grep -n '>' .env | head -10
  ERRORS=$((ERRORS+1))
else
  echo -e "  \033[0;32m✅ Không có ký tự > wrap dòng trong value env\033[0m"
fi

# Kiểm tra 2: CRLF dấu \r
CRLF_N="$(grep -cU $'\r' .env 2>/dev/null || echo "0")"
if [[ "$CRLF_N" -gt 0 ]]; then
  echo -e "  \033[0;31m❌ File vẫn còn $CRLF_N dòng CRLF Windows — tự fix lại:\033[0m"
  sed -i 's/\r$//' .env
  echo -e "  \033[0;32m  → Đã tự động fix bằng sed.\033[0m"
else
  echo -e "  \033[0;32m✅ Không còn CRLF Windows (100% LF Unix)\033[0m"
fi

# Kiểm tra 3: DATABASE_URL có đúng format không?
if grep -Eq '^DATABASE_URL=postgresql://[^:]+:[^@]+@[^:]+:[0-9]+/[a-zA-Z0-9_]+' .env; then
  echo -e "  \033[0;32m✅ DATABASE_URL đúng format chuẩn (user:pass@host:port/dbname)\033[0m"
else
  echo -e "  \033[0;31m❌ DATABASE_URL KHÔNG đúng format — cần sửa thủ công:\033[0m"
  grep -n 'DATABASE_URL=' .env
  echo -e "  \033[0;33m  → Format đúng: postgresql://kdpd_user:PASSWORD@localhost:5433/kdpd_db?schema=public\033[0m"
  ERRORS=$((ERRORS+1))
fi

# Kiểm tra 4: CSRF_ORIGIN không chứa TRUST_PROXY
if grep -Eq '^CSRF_ORIGIN=.*TRUST_PROXY' .env; then
  echo -e "  \033[0;31m❌ CSRF_ORIGIN bị gộp dòng với TRUST_PROXY — cần sửa thủ công\033[0m"
  grep -n 'CSRF_ORIGIN=' .env
  ERRORS=$((ERRORS+1))
else
  echo -e "  \033[0;32m✅ CSRF_ORIGIN đúng, không bị gộp TRUST_PROXY\033[0m"
fi

# Kiểm tra 5: TRUST_PROXY có dòng riêng biệt không?
if grep -Eq '^TRUST_PROXY=1$' .env; then
  echo -e "  \033[0;32m✅ TRUST_PROXY có dòng riêng, OK.\033[0m"
else
  echo -e "  \033[0;33m⚠️  TRUST_PROXY không có dòng riêng (port 5000 vẫn chạy bình thường nhưng nginx real IP sai).\033[0m"
fi

echo ""
if [[ $ERRORS -eq 0 ]]; then
  echo -e "\033[1;32m🎉 .env sạch — 0 lỗi! Bây giờ chạy lại kdpd-one-click-fix.sh:\033[0m"
  echo -e "    \033[1;36m  sudo bash ./kdpd-one-click-fix.sh 2>&1 | tee kdpd-final-fix-2.log\033[0m"
else
  echo -e "\033[1;31m⚠️  CÒN $ERRORS lỗi cần sửa thủ công trong .env. Hãy xem các dòng màu đỏ ở trên.\033[0m"
  echo -e "\033[1;33m  Sau khi sửa xong: bash kdpd-generate-clean-env.sh 1 lần nữa để double-check.\033[0m"
  exit 10
fi
